# Generated by Django 5.1.4 on 2024-12-06 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Periodo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_periodo", models.CharField(max_length=50)),
                ("fecha_inicio", models.DateField()),
                ("fecha_finalizacion", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="FechasImportantes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_evento", models.CharField(max_length=200)),
                ("fecha", models.DateField()),
                (
                    "periodo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="important_dates",
                        to="chatapp.periodo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Examen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo_examen", models.CharField(max_length=200)),
                ("modalidad", models.CharField(max_length=200)),
                ("fecha_inicio", models.DateField()),
                ("fecha_finalizacion", models.DateField(blank=True, null=True)),
                (
                    "periodo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exams",
                        to="chatapp.periodo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_evento", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("fecha_inicio", models.DateField()),
                ("fecha_finalizacion", models.DateField(blank=True, null=True)),
                (
                    "tipo_evento",
                    models.CharField(
                        choices=[
                            ("MAT", "Matrícula"),
                            ("EXA", "Examen"),
                            ("IND", "Inducción"),
                            ("GRD", "Graduación"),
                            ("OTR", "Otro"),
                        ],
                        default="OTR",
                        help_text="Selecciona el tipo de evento",
                        max_length=3,
                    ),
                ),
                (
                    "periodo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="chatapp.periodo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RequisitosGraduacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.TextField()),
                ("fecha_tentativa", models.DateField()),
                (
                    "periodo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="graduation_requirements",
                        to="chatapp.periodo",
                    ),
                ),
            ],
        ),
    ]
