# Generated by Django 5.1.4 on 2024-12-06 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatapp", "0002_profesores_cursos_seccion"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cursos",
            name="profesor",
        ),
        migrations.RemoveField(
            model_name="seccion",
            name="curso",
        ),
        migrations.RemoveField(
            model_name="seccion",
            name="periodo",
        ),
        migrations.DeleteModel(
            name="Profesores",
        ),
        migrations.DeleteModel(
            name="Cursos",
        ),
        migrations.DeleteModel(
            name="Seccion",
        ),
    ]
