# Generated by Django 5.1.4 on 2024-12-07 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatapp", "0003_remove_cursos_profesor_remove_seccion_curso_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mensajes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pregunta", models.TextField(max_length=500)),
                ("respuesta", models.TextField(max_length=500)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
